# Site settings and author sidebar. Page content lives in _pages/.
locale: en-US
site_theme: air
title: Ziyu Li
title_separator: "-"
name: Ziyu Li
description: Ziyu Li academic portfolio
url: https://ziyuli22.github.io
baseurl: ''
author:
  avatar: professional2021.png
  name: Ziyu Li
  pronouns: she/her
  bio: spatial statics, ML in hydrology, computational mathematics
  location: Boulder, Colorado, USA
  employer: Colorado School of Mines
  email: ziyu_li@mines.edu
  googlescholar: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=KgRaZK4AAAAJ&scilu=&scisig=AOcXxEUAAAAAapo5LWmheBveEeuSFbOuHqLxZBU&gmla=AKCpqFwMRjqFjp2v-tLblrMeaFIYdLeCq2-dJ6IkkGwJjTfiJR6EcIG4IAgoHimNaNUi50l3iIsQnjQeKzIf1mTOiQiiWnMIxmrkYuM&sciund=13864761810827963777
  orcid: https://orcid.org/0000-0001-9844-1215
  github: ziyuli22
encoding: utf-8
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
timezone: Etc/UTC
compress_html:
  clippings: all
  ignore:
    envs: development
include:
- _pages
- files
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- package.json
- package-lock.json
- node_modules
- vendor
- assets/js/_main.js
- assets/js/plugins
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: true
atom_feed:
  hide: true
plugins:
- jekyll-sitemap
- jekyll-redirect-from
